/* 
 * APG API
 *
 * This is a APG (Ayria Payment Gateway) API SDK.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ayriaplatform.apg.Api;
using com.ayriaplatform.apg.Model;
using com.ayriaplatform.apg.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ayriaplatform.apg.Test
{
    /// <summary>
    ///  Class for testing AyriaPaymentV1CancelCommand
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AyriaPaymentV1CancelCommandTests
    {
        // TODO uncomment below to declare an instance variable for AyriaPaymentV1CancelCommand
        //private AyriaPaymentV1CancelCommand instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AyriaPaymentV1CancelCommand
            //instance = new AyriaPaymentV1CancelCommand();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AyriaPaymentV1CancelCommand
        /// </summary>
        [Test]
        public void AyriaPaymentV1CancelCommandInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" AyriaPaymentV1CancelCommand
            //Assert.IsInstanceOf(typeof(AyriaPaymentV1CancelCommand), instance);
        }


        /// <summary>
        /// Test the property 'ReferenceCode'
        /// </summary>
        [Test]
        public void ReferenceCodeTest()
        {
            // TODO unit test for the property 'ReferenceCode'
        }
        /// <summary>
        /// Test the property 'CancelDescription'
        /// </summary>
        [Test]
        public void CancelDescriptionTest()
        {
            // TODO unit test for the property 'CancelDescription'
        }

    }

}
