/* 
 * APG API
 *
 * This is a APG (Ayria Payment Gateway) API SDK.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ayriaplatform.apg.Api;
using com.ayriaplatform.apg.Model;
using com.ayriaplatform.apg.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ayriaplatform.apg.Test
{
    /// <summary>
    ///  Class for testing AyriaPaymentV1DTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AyriaPaymentV1DTOTests
    {
        // TODO uncomment below to declare an instance variable for AyriaPaymentV1DTO
        //private AyriaPaymentV1DTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AyriaPaymentV1DTO
            //instance = new AyriaPaymentV1DTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AyriaPaymentV1DTO
        /// </summary>
        [Test]
        public void AyriaPaymentV1DTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" AyriaPaymentV1DTO
            //Assert.IsInstanceOf(typeof(AyriaPaymentV1DTO), instance);
        }


        /// <summary>
        /// Test the property 'ReferralCode'
        /// </summary>
        [Test]
        public void ReferralCodeTest()
        {
            // TODO unit test for the property 'ReferralCode'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'PayerMobile'
        /// </summary>
        [Test]
        public void PayerMobileTest()
        {
            // TODO unit test for the property 'PayerMobile'
        }
        /// <summary>
        /// Test the property 'TrackingNumber'
        /// </summary>
        [Test]
        public void TrackingNumberTest()
        {
            // TODO unit test for the property 'TrackingNumber'
        }
        /// <summary>
        /// Test the property 'ReferenceCode'
        /// </summary>
        [Test]
        public void ReferenceCodeTest()
        {
            // TODO unit test for the property 'ReferenceCode'
        }
        /// <summary>
        /// Test the property 'PayeeName'
        /// </summary>
        [Test]
        public void PayeeNameTest()
        {
            // TODO unit test for the property 'PayeeName'
        }
        /// <summary>
        /// Test the property 'PayerName'
        /// </summary>
        [Test]
        public void PayerNameTest()
        {
            // TODO unit test for the property 'PayerName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ExtraData'
        /// </summary>
        [Test]
        public void ExtraDataTest()
        {
            // TODO unit test for the property 'ExtraData'
        }
        /// <summary>
        /// Test the property 'PaymentNumber'
        /// </summary>
        [Test]
        public void PaymentNumberTest()
        {
            // TODO unit test for the property 'PaymentNumber'
        }
        /// <summary>
        /// Test the property 'Paid'
        /// </summary>
        [Test]
        public void PaidTest()
        {
            // TODO unit test for the property 'Paid'
        }
        /// <summary>
        /// Test the property 'Canceled'
        /// </summary>
        [Test]
        public void CanceledTest()
        {
            // TODO unit test for the property 'Canceled'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Test]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }
        /// <summary>
        /// Test the property 'PaymentUrl'
        /// </summary>
        [Test]
        public void PaymentUrlTest()
        {
            // TODO unit test for the property 'PaymentUrl'
        }
        /// <summary>
        /// Test the property 'CancelDescription'
        /// </summary>
        [Test]
        public void CancelDescriptionTest()
        {
            // TODO unit test for the property 'CancelDescription'
        }
        /// <summary>
        /// Test the property 'Kalas'
        /// </summary>
        [Test]
        public void KalasTest()
        {
            // TODO unit test for the property 'Kalas'
        }

    }

}
