/* 
 * APG API
 *
 * This is a APG (Ayria Payment Gateway) API SDK.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ayriaplatform.apg.Api;
using com.ayriaplatform.apg.Model;
using com.ayriaplatform.apg.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ayriaplatform.apg.Test
{
    /// <summary>
    ///  Class for testing AyriaPaymentV1Command
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AyriaPaymentV1CommandTests
    {
        // TODO uncomment below to declare an instance variable for AyriaPaymentV1Command
        //private AyriaPaymentV1Command instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AyriaPaymentV1Command
            //instance = new AyriaPaymentV1Command();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AyriaPaymentV1Command
        /// </summary>
        [Test]
        public void AyriaPaymentV1CommandInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" AyriaPaymentV1Command
            //Assert.IsInstanceOf(typeof(AyriaPaymentV1Command), instance);
        }


        /// <summary>
        /// Test the property 'ReferralCode'
        /// </summary>
        [Test]
        public void ReferralCodeTest()
        {
            // TODO unit test for the property 'ReferralCode'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'PayerMobile'
        /// </summary>
        [Test]
        public void PayerMobileTest()
        {
            // TODO unit test for the property 'PayerMobile'
        }
        /// <summary>
        /// Test the property 'PayerName'
        /// </summary>
        [Test]
        public void PayerNameTest()
        {
            // TODO unit test for the property 'PayerName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'PaymentNumber'
        /// </summary>
        [Test]
        public void PaymentNumberTest()
        {
            // TODO unit test for the property 'PaymentNumber'
        }
        /// <summary>
        /// Test the property 'ExtraData'
        /// </summary>
        [Test]
        public void ExtraDataTest()
        {
            // TODO unit test for the property 'ExtraData'
        }
        /// <summary>
        /// Test the property 'Kalas'
        /// </summary>
        [Test]
        public void KalasTest()
        {
            // TODO unit test for the property 'Kalas'
        }

    }

}
