/* 
 * APG API
 *
 * This is a APG (Ayria Payment Gateway) API SDK.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ayriaplatform.apg.Api;
using com.ayriaplatform.apg.Model;
using com.ayriaplatform.apg.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ayriaplatform.apg.Test
{
    /// <summary>
    ///  Class for testing AyriaPaymentV1KalaDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AyriaPaymentV1KalaDTOTests
    {
        // TODO uncomment below to declare an instance variable for AyriaPaymentV1KalaDTO
        //private AyriaPaymentV1KalaDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AyriaPaymentV1KalaDTO
            //instance = new AyriaPaymentV1KalaDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AyriaPaymentV1KalaDTO
        /// </summary>
        [Test]
        public void AyriaPaymentV1KalaDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" AyriaPaymentV1KalaDTO
            //Assert.IsInstanceOf(typeof(AyriaPaymentV1KalaDTO), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Test]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'Brand'
        /// </summary>
        [Test]
        public void BrandTest()
        {
            // TODO unit test for the property 'Brand'
        }
        /// <summary>
        /// Test the property 'Service'
        /// </summary>
        [Test]
        public void ServiceTest()
        {
            // TODO unit test for the property 'Service'
        }

    }

}
