/* 
 * APG API
 *
 * This is a APG (Ayria Payment Gateway) API SDK.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using RestSharp;
using com.ayriaplatform.apg.Client;
using com.ayriaplatform.apg.Model;

namespace com.ayriaplatform.apg.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPaymentApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Find payment with referenceCode
        /// </summary>
        /// <remarks>
        /// Returns a single payment
        /// </remarks>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="referenceCode">ReferenceCode of payment to return</param>
        /// <returns>AyriaPaymentV1DTO</returns>
        AyriaPaymentV1DTO GetPaymentByReferenceCode (string APG_WALLET_ID, string referenceCode);

        /// <summary>
        /// Find payment with referenceCode
        /// </summary>
        /// <remarks>
        /// Returns a single payment
        /// </remarks>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="referenceCode">ReferenceCode of payment to return</param>
        /// <returns>ApiResponse of AyriaPaymentV1DTO</returns>
        ApiResponse<AyriaPaymentV1DTO> GetPaymentByReferenceCodeWithHttpInfo (string APG_WALLET_ID, string referenceCode);
        /// <summary>
        /// List of payments between given dates
        /// </summary>
        /// <remarks>
        /// Returns a payment list
        /// </remarks>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="page">Page number (optional)</param>
        /// <param name="size">Page size (optional)</param>
        /// <param name="sort">Sort column and direction (optional)</param>
        /// <param name="createdDateGreaterThan">Created date greater than (optional)</param>
        /// <param name="createdDateToLessThanOrEqual">Created date less than or equal (optional)</param>
        /// <returns>List&lt;AyriaPaymentV1DTO&gt;</returns>
        List<AyriaPaymentV1DTO> GetPayments (string APG_WALLET_ID, string page = default(string), string size = default(string), string sort = default(string), string createdDateGreaterThan = default(string), string createdDateToLessThanOrEqual = default(string));

        /// <summary>
        /// List of payments between given dates
        /// </summary>
        /// <remarks>
        /// Returns a payment list
        /// </remarks>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="page">Page number (optional)</param>
        /// <param name="size">Page size (optional)</param>
        /// <param name="sort">Sort column and direction (optional)</param>
        /// <param name="createdDateGreaterThan">Created date greater than (optional)</param>
        /// <param name="createdDateToLessThanOrEqual">Created date less than or equal (optional)</param>
        /// <returns>ApiResponse of List&lt;AyriaPaymentV1DTO&gt;</returns>
        ApiResponse<List<AyriaPaymentV1DTO>> GetPaymentsWithHttpInfo (string APG_WALLET_ID, string page = default(string), string size = default(string), string sort = default(string), string createdDateGreaterThan = default(string), string createdDateToLessThanOrEqual = default(string));
        /// <summary>
        /// Cancel a  payment
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="ayriaPaymentV1CancelCommand"> (optional)</param>
        /// <returns>AyriaPaymentV1DTO</returns>
        AyriaPaymentV1DTO PaymentCancel (string APG_WALLET_ID, AyriaPaymentV1CancelCommand ayriaPaymentV1CancelCommand = default(AyriaPaymentV1CancelCommand));

        /// <summary>
        /// Cancel a  payment
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="ayriaPaymentV1CancelCommand"> (optional)</param>
        /// <returns>ApiResponse of AyriaPaymentV1DTO</returns>
        ApiResponse<AyriaPaymentV1DTO> PaymentCancelWithHttpInfo (string APG_WALLET_ID, AyriaPaymentV1CancelCommand ayriaPaymentV1CancelCommand = default(AyriaPaymentV1CancelCommand));
        /// <summary>
        /// Add a new payment
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="ayriaPaymentV1Command"> (optional)</param>
        /// <returns>AyriaPaymentV1DTO</returns>
        AyriaPaymentV1DTO PaymentCreate (string APG_WALLET_ID, AyriaPaymentV1Command ayriaPaymentV1Command = default(AyriaPaymentV1Command));

        /// <summary>
        /// Add a new payment
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="ayriaPaymentV1Command"> (optional)</param>
        /// <returns>ApiResponse of AyriaPaymentV1DTO</returns>
        ApiResponse<AyriaPaymentV1DTO> PaymentCreateWithHttpInfo (string APG_WALLET_ID, AyriaPaymentV1Command ayriaPaymentV1Command = default(AyriaPaymentV1Command));
        /// <summary>
        /// Verify payment with referenceCode
        /// </summary>
        /// <remarks>
        /// Returns a single payment
        /// </remarks>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="referenceCode">ReferenceCode of payment to verify</param>
        /// <returns>AyriaPaymentV1DTO</returns>
        AyriaPaymentV1DTO VerifyPaymentByReferenceCode (string APG_WALLET_ID, string referenceCode);

        /// <summary>
        /// Verify payment with referenceCode
        /// </summary>
        /// <remarks>
        /// Returns a single payment
        /// </remarks>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="referenceCode">ReferenceCode of payment to verify</param>
        /// <returns>ApiResponse of AyriaPaymentV1DTO</returns>
        ApiResponse<AyriaPaymentV1DTO> VerifyPaymentByReferenceCodeWithHttpInfo (string APG_WALLET_ID, string referenceCode);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Find payment with referenceCode
        /// </summary>
        /// <remarks>
        /// Returns a single payment
        /// </remarks>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="referenceCode">ReferenceCode of payment to return</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of AyriaPaymentV1DTO</returns>
        System.Threading.Tasks.Task<AyriaPaymentV1DTO> GetPaymentByReferenceCodeAsync (string APG_WALLET_ID, string referenceCode, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Find payment with referenceCode
        /// </summary>
        /// <remarks>
        /// Returns a single payment
        /// </remarks>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="referenceCode">ReferenceCode of payment to return</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (AyriaPaymentV1DTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<AyriaPaymentV1DTO>> GetPaymentByReferenceCodeWithHttpInfoAsync (string APG_WALLET_ID, string referenceCode, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// List of payments between given dates
        /// </summary>
        /// <remarks>
        /// Returns a payment list
        /// </remarks>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="page">Page number (optional)</param>
        /// <param name="size">Page size (optional)</param>
        /// <param name="sort">Sort column and direction (optional)</param>
        /// <param name="createdDateGreaterThan">Created date greater than (optional)</param>
        /// <param name="createdDateToLessThanOrEqual">Created date less than or equal (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of List&lt;AyriaPaymentV1DTO&gt;</returns>
        System.Threading.Tasks.Task<List<AyriaPaymentV1DTO>> GetPaymentsAsync (string APG_WALLET_ID, string page = default(string), string size = default(string), string sort = default(string), string createdDateGreaterThan = default(string), string createdDateToLessThanOrEqual = default(string), CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// List of payments between given dates
        /// </summary>
        /// <remarks>
        /// Returns a payment list
        /// </remarks>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="page">Page number (optional)</param>
        /// <param name="size">Page size (optional)</param>
        /// <param name="sort">Sort column and direction (optional)</param>
        /// <param name="createdDateGreaterThan">Created date greater than (optional)</param>
        /// <param name="createdDateToLessThanOrEqual">Created date less than or equal (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (List&lt;AyriaPaymentV1DTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<AyriaPaymentV1DTO>>> GetPaymentsWithHttpInfoAsync (string APG_WALLET_ID, string page = default(string), string size = default(string), string sort = default(string), string createdDateGreaterThan = default(string), string createdDateToLessThanOrEqual = default(string), CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Cancel a  payment
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="ayriaPaymentV1CancelCommand"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of AyriaPaymentV1DTO</returns>
        System.Threading.Tasks.Task<AyriaPaymentV1DTO> PaymentCancelAsync (string APG_WALLET_ID, AyriaPaymentV1CancelCommand ayriaPaymentV1CancelCommand = default(AyriaPaymentV1CancelCommand), CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Cancel a  payment
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="ayriaPaymentV1CancelCommand"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (AyriaPaymentV1DTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<AyriaPaymentV1DTO>> PaymentCancelWithHttpInfoAsync (string APG_WALLET_ID, AyriaPaymentV1CancelCommand ayriaPaymentV1CancelCommand = default(AyriaPaymentV1CancelCommand), CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Add a new payment
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="ayriaPaymentV1Command"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of AyriaPaymentV1DTO</returns>
        System.Threading.Tasks.Task<AyriaPaymentV1DTO> PaymentCreateAsync (string APG_WALLET_ID, AyriaPaymentV1Command ayriaPaymentV1Command = default(AyriaPaymentV1Command), CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Add a new payment
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="ayriaPaymentV1Command"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (AyriaPaymentV1DTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<AyriaPaymentV1DTO>> PaymentCreateWithHttpInfoAsync (string APG_WALLET_ID, AyriaPaymentV1Command ayriaPaymentV1Command = default(AyriaPaymentV1Command), CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Verify payment with referenceCode
        /// </summary>
        /// <remarks>
        /// Returns a single payment
        /// </remarks>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="referenceCode">ReferenceCode of payment to verify</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of AyriaPaymentV1DTO</returns>
        System.Threading.Tasks.Task<AyriaPaymentV1DTO> VerifyPaymentByReferenceCodeAsync (string APG_WALLET_ID, string referenceCode, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Verify payment with referenceCode
        /// </summary>
        /// <remarks>
        /// Returns a single payment
        /// </remarks>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="referenceCode">ReferenceCode of payment to verify</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (AyriaPaymentV1DTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<AyriaPaymentV1DTO>> VerifyPaymentByReferenceCodeWithHttpInfoAsync (string APG_WALLET_ID, string referenceCode, CancellationToken cancellationToken = default(CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PaymentApi : IPaymentApi
    {
        private com.ayriaplatform.apg.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PaymentApi(String basePath)
        {
            this.Configuration = new com.ayriaplatform.apg.Client.Configuration { BasePath = basePath };

            ExceptionFactory = com.ayriaplatform.apg.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentApi"/> class
        /// </summary>
        /// <returns></returns>
        public PaymentApi()
        {
            this.Configuration = com.ayriaplatform.apg.Client.Configuration.Default;

            ExceptionFactory = com.ayriaplatform.apg.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public PaymentApi(com.ayriaplatform.apg.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = com.ayriaplatform.apg.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = com.ayriaplatform.apg.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public com.ayriaplatform.apg.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public com.ayriaplatform.apg.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Find payment with referenceCode Returns a single payment
        /// </summary>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="referenceCode">ReferenceCode of payment to return</param>
        /// <returns>AyriaPaymentV1DTO</returns>
        public AyriaPaymentV1DTO GetPaymentByReferenceCode (string APG_WALLET_ID, string referenceCode)
        {
             ApiResponse<AyriaPaymentV1DTO> localVarResponse = GetPaymentByReferenceCodeWithHttpInfo(APG_WALLET_ID, referenceCode);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Find payment with referenceCode Returns a single payment
        /// </summary>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="referenceCode">ReferenceCode of payment to return</param>
        /// <returns>ApiResponse of AyriaPaymentV1DTO</returns>
        public ApiResponse<AyriaPaymentV1DTO> GetPaymentByReferenceCodeWithHttpInfo (string APG_WALLET_ID, string referenceCode)
        {
            // verify the required parameter 'APG_WALLET_ID' is set
            if (APG_WALLET_ID == null)
                throw new ApiException(400, "Missing required parameter 'APG_WALLET_ID' when calling PaymentApi->GetPaymentByReferenceCode");
            // verify the required parameter 'referenceCode' is set
            if (referenceCode == null)
                throw new ApiException(400, "Missing required parameter 'referenceCode' when calling PaymentApi->GetPaymentByReferenceCode");

            var localVarPath = "/get/{referenceCode}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (referenceCode != null) localVarPathParams.Add("referenceCode", this.Configuration.ApiClient.ParameterToString(referenceCode)); // path parameter
            if (APG_WALLET_ID != null) localVarHeaderParams.Add("APG-WALLET-ID", this.Configuration.ApiClient.ParameterToString(APG_WALLET_ID)); // header parameter

            // authentication (APG-API-KEY) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("APG-API-KEY")))
            {
                localVarHeaderParams["APG-API-KEY"] = this.Configuration.GetApiKeyWithPrefix("APG-API-KEY");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetPaymentByReferenceCode", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AyriaPaymentV1DTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (AyriaPaymentV1DTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AyriaPaymentV1DTO)));
        }

        /// <summary>
        /// Find payment with referenceCode Returns a single payment
        /// </summary>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="referenceCode">ReferenceCode of payment to return</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of AyriaPaymentV1DTO</returns>
        public async System.Threading.Tasks.Task<AyriaPaymentV1DTO> GetPaymentByReferenceCodeAsync (string APG_WALLET_ID, string referenceCode, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<AyriaPaymentV1DTO> localVarResponse = await GetPaymentByReferenceCodeWithHttpInfoAsync(APG_WALLET_ID, referenceCode, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Find payment with referenceCode Returns a single payment
        /// </summary>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="referenceCode">ReferenceCode of payment to return</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (AyriaPaymentV1DTO)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AyriaPaymentV1DTO>> GetPaymentByReferenceCodeWithHttpInfoAsync (string APG_WALLET_ID, string referenceCode, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'APG_WALLET_ID' is set
            if (APG_WALLET_ID == null)
                throw new ApiException(400, "Missing required parameter 'APG_WALLET_ID' when calling PaymentApi->GetPaymentByReferenceCode");
            // verify the required parameter 'referenceCode' is set
            if (referenceCode == null)
                throw new ApiException(400, "Missing required parameter 'referenceCode' when calling PaymentApi->GetPaymentByReferenceCode");

            var localVarPath = "/get/{referenceCode}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (referenceCode != null) localVarPathParams.Add("referenceCode", this.Configuration.ApiClient.ParameterToString(referenceCode)); // path parameter
            if (APG_WALLET_ID != null) localVarHeaderParams.Add("APG-WALLET-ID", this.Configuration.ApiClient.ParameterToString(APG_WALLET_ID)); // header parameter

            // authentication (APG-API-KEY) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("APG-API-KEY")))
            {
                localVarHeaderParams["APG-API-KEY"] = this.Configuration.GetApiKeyWithPrefix("APG-API-KEY");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetPaymentByReferenceCode", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AyriaPaymentV1DTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (AyriaPaymentV1DTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AyriaPaymentV1DTO)));
        }

        /// <summary>
        /// List of payments between given dates Returns a payment list
        /// </summary>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="page">Page number (optional)</param>
        /// <param name="size">Page size (optional)</param>
        /// <param name="sort">Sort column and direction (optional)</param>
        /// <param name="createdDateGreaterThan">Created date greater than (optional)</param>
        /// <param name="createdDateToLessThanOrEqual">Created date less than or equal (optional)</param>
        /// <returns>List&lt;AyriaPaymentV1DTO&gt;</returns>
        public List<AyriaPaymentV1DTO> GetPayments (string APG_WALLET_ID, string page = default(string), string size = default(string), string sort = default(string), string createdDateGreaterThan = default(string), string createdDateToLessThanOrEqual = default(string))
        {
             ApiResponse<List<AyriaPaymentV1DTO>> localVarResponse = GetPaymentsWithHttpInfo(APG_WALLET_ID, page, size, sort, createdDateGreaterThan, createdDateToLessThanOrEqual);
             return localVarResponse.Data;
        }

        /// <summary>
        /// List of payments between given dates Returns a payment list
        /// </summary>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="page">Page number (optional)</param>
        /// <param name="size">Page size (optional)</param>
        /// <param name="sort">Sort column and direction (optional)</param>
        /// <param name="createdDateGreaterThan">Created date greater than (optional)</param>
        /// <param name="createdDateToLessThanOrEqual">Created date less than or equal (optional)</param>
        /// <returns>ApiResponse of List&lt;AyriaPaymentV1DTO&gt;</returns>
        public ApiResponse<List<AyriaPaymentV1DTO>> GetPaymentsWithHttpInfo (string APG_WALLET_ID, string page = default(string), string size = default(string), string sort = default(string), string createdDateGreaterThan = default(string), string createdDateToLessThanOrEqual = default(string))
        {
            // verify the required parameter 'APG_WALLET_ID' is set
            if (APG_WALLET_ID == null)
                throw new ApiException(400, "Missing required parameter 'APG_WALLET_ID' when calling PaymentApi->GetPayments");

            var localVarPath = "/list";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter
            if (size != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "size", size)); // query parameter
            if (sort != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "sort", sort)); // query parameter
            if (createdDateGreaterThan != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "createdDate.greaterThan", createdDateGreaterThan)); // query parameter
            if (createdDateToLessThanOrEqual != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "createdDateTo.lessThanOrEqual", createdDateToLessThanOrEqual)); // query parameter
            if (APG_WALLET_ID != null) localVarHeaderParams.Add("APG-WALLET-ID", this.Configuration.ApiClient.ParameterToString(APG_WALLET_ID)); // header parameter

            // authentication (APG-API-KEY) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("APG-API-KEY")))
            {
                localVarHeaderParams["APG-API-KEY"] = this.Configuration.GetApiKeyWithPrefix("APG-API-KEY");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetPayments", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<AyriaPaymentV1DTO>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<AyriaPaymentV1DTO>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<AyriaPaymentV1DTO>)));
        }

        /// <summary>
        /// List of payments between given dates Returns a payment list
        /// </summary>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="page">Page number (optional)</param>
        /// <param name="size">Page size (optional)</param>
        /// <param name="sort">Sort column and direction (optional)</param>
        /// <param name="createdDateGreaterThan">Created date greater than (optional)</param>
        /// <param name="createdDateToLessThanOrEqual">Created date less than or equal (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of List&lt;AyriaPaymentV1DTO&gt;</returns>
        public async System.Threading.Tasks.Task<List<AyriaPaymentV1DTO>> GetPaymentsAsync (string APG_WALLET_ID, string page = default(string), string size = default(string), string sort = default(string), string createdDateGreaterThan = default(string), string createdDateToLessThanOrEqual = default(string), CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<List<AyriaPaymentV1DTO>> localVarResponse = await GetPaymentsWithHttpInfoAsync(APG_WALLET_ID, page, size, sort, createdDateGreaterThan, createdDateToLessThanOrEqual, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// List of payments between given dates Returns a payment list
        /// </summary>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="page">Page number (optional)</param>
        /// <param name="size">Page size (optional)</param>
        /// <param name="sort">Sort column and direction (optional)</param>
        /// <param name="createdDateGreaterThan">Created date greater than (optional)</param>
        /// <param name="createdDateToLessThanOrEqual">Created date less than or equal (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (List&lt;AyriaPaymentV1DTO&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<AyriaPaymentV1DTO>>> GetPaymentsWithHttpInfoAsync (string APG_WALLET_ID, string page = default(string), string size = default(string), string sort = default(string), string createdDateGreaterThan = default(string), string createdDateToLessThanOrEqual = default(string), CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'APG_WALLET_ID' is set
            if (APG_WALLET_ID == null)
                throw new ApiException(400, "Missing required parameter 'APG_WALLET_ID' when calling PaymentApi->GetPayments");

            var localVarPath = "/list";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter
            if (size != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "size", size)); // query parameter
            if (sort != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "sort", sort)); // query parameter
            if (createdDateGreaterThan != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "createdDate.greaterThan", createdDateGreaterThan)); // query parameter
            if (createdDateToLessThanOrEqual != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "createdDateTo.lessThanOrEqual", createdDateToLessThanOrEqual)); // query parameter
            if (APG_WALLET_ID != null) localVarHeaderParams.Add("APG-WALLET-ID", this.Configuration.ApiClient.ParameterToString(APG_WALLET_ID)); // header parameter

            // authentication (APG-API-KEY) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("APG-API-KEY")))
            {
                localVarHeaderParams["APG-API-KEY"] = this.Configuration.GetApiKeyWithPrefix("APG-API-KEY");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetPayments", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<AyriaPaymentV1DTO>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<AyriaPaymentV1DTO>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<AyriaPaymentV1DTO>)));
        }

        /// <summary>
        /// Cancel a  payment 
        /// </summary>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="ayriaPaymentV1CancelCommand"> (optional)</param>
        /// <returns>AyriaPaymentV1DTO</returns>
        public AyriaPaymentV1DTO PaymentCancel (string APG_WALLET_ID, AyriaPaymentV1CancelCommand ayriaPaymentV1CancelCommand = default(AyriaPaymentV1CancelCommand))
        {
             ApiResponse<AyriaPaymentV1DTO> localVarResponse = PaymentCancelWithHttpInfo(APG_WALLET_ID, ayriaPaymentV1CancelCommand);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Cancel a  payment 
        /// </summary>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="ayriaPaymentV1CancelCommand"> (optional)</param>
        /// <returns>ApiResponse of AyriaPaymentV1DTO</returns>
        public ApiResponse<AyriaPaymentV1DTO> PaymentCancelWithHttpInfo (string APG_WALLET_ID, AyriaPaymentV1CancelCommand ayriaPaymentV1CancelCommand = default(AyriaPaymentV1CancelCommand))
        {
            // verify the required parameter 'APG_WALLET_ID' is set
            if (APG_WALLET_ID == null)
                throw new ApiException(400, "Missing required parameter 'APG_WALLET_ID' when calling PaymentApi->PaymentCancel");

            var localVarPath = "/cancel";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (APG_WALLET_ID != null) localVarHeaderParams.Add("APG-WALLET-ID", this.Configuration.ApiClient.ParameterToString(APG_WALLET_ID)); // header parameter
            if (ayriaPaymentV1CancelCommand != null && ayriaPaymentV1CancelCommand.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(ayriaPaymentV1CancelCommand); // http body (model) parameter
            }
            else
            {
                localVarPostBody = ayriaPaymentV1CancelCommand; // byte array
            }

            // authentication (APG-API-KEY) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("APG-API-KEY")))
            {
                localVarHeaderParams["APG-API-KEY"] = this.Configuration.GetApiKeyWithPrefix("APG-API-KEY");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PaymentCancel", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AyriaPaymentV1DTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (AyriaPaymentV1DTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AyriaPaymentV1DTO)));
        }

        /// <summary>
        /// Cancel a  payment 
        /// </summary>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="ayriaPaymentV1CancelCommand"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of AyriaPaymentV1DTO</returns>
        public async System.Threading.Tasks.Task<AyriaPaymentV1DTO> PaymentCancelAsync (string APG_WALLET_ID, AyriaPaymentV1CancelCommand ayriaPaymentV1CancelCommand = default(AyriaPaymentV1CancelCommand), CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<AyriaPaymentV1DTO> localVarResponse = await PaymentCancelWithHttpInfoAsync(APG_WALLET_ID, ayriaPaymentV1CancelCommand, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Cancel a  payment 
        /// </summary>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="ayriaPaymentV1CancelCommand"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (AyriaPaymentV1DTO)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AyriaPaymentV1DTO>> PaymentCancelWithHttpInfoAsync (string APG_WALLET_ID, AyriaPaymentV1CancelCommand ayriaPaymentV1CancelCommand = default(AyriaPaymentV1CancelCommand), CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'APG_WALLET_ID' is set
            if (APG_WALLET_ID == null)
                throw new ApiException(400, "Missing required parameter 'APG_WALLET_ID' when calling PaymentApi->PaymentCancel");

            var localVarPath = "/cancel";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (APG_WALLET_ID != null) localVarHeaderParams.Add("APG-WALLET-ID", this.Configuration.ApiClient.ParameterToString(APG_WALLET_ID)); // header parameter
            if (ayriaPaymentV1CancelCommand != null && ayriaPaymentV1CancelCommand.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(ayriaPaymentV1CancelCommand); // http body (model) parameter
            }
            else
            {
                localVarPostBody = ayriaPaymentV1CancelCommand; // byte array
            }

            // authentication (APG-API-KEY) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("APG-API-KEY")))
            {
                localVarHeaderParams["APG-API-KEY"] = this.Configuration.GetApiKeyWithPrefix("APG-API-KEY");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PaymentCancel", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AyriaPaymentV1DTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (AyriaPaymentV1DTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AyriaPaymentV1DTO)));
        }

        /// <summary>
        /// Add a new payment 
        /// </summary>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="ayriaPaymentV1Command"> (optional)</param>
        /// <returns>AyriaPaymentV1DTO</returns>
        public AyriaPaymentV1DTO PaymentCreate (string APG_WALLET_ID, AyriaPaymentV1Command ayriaPaymentV1Command = default(AyriaPaymentV1Command))
        {
             ApiResponse<AyriaPaymentV1DTO> localVarResponse = PaymentCreateWithHttpInfo(APG_WALLET_ID, ayriaPaymentV1Command);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Add a new payment 
        /// </summary>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="ayriaPaymentV1Command"> (optional)</param>
        /// <returns>ApiResponse of AyriaPaymentV1DTO</returns>
        public ApiResponse<AyriaPaymentV1DTO> PaymentCreateWithHttpInfo (string APG_WALLET_ID, AyriaPaymentV1Command ayriaPaymentV1Command = default(AyriaPaymentV1Command))
        {
            // verify the required parameter 'APG_WALLET_ID' is set
            if (APG_WALLET_ID == null)
                throw new ApiException(400, "Missing required parameter 'APG_WALLET_ID' when calling PaymentApi->PaymentCreate");

            var localVarPath = "/create";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (APG_WALLET_ID != null) localVarHeaderParams.Add("APG-WALLET-ID", this.Configuration.ApiClient.ParameterToString(APG_WALLET_ID)); // header parameter
            if (ayriaPaymentV1Command != null && ayriaPaymentV1Command.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(ayriaPaymentV1Command); // http body (model) parameter
            }
            else
            {
                localVarPostBody = ayriaPaymentV1Command; // byte array
            }

            // authentication (APG-API-KEY) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("APG-API-KEY")))
            {
                localVarHeaderParams["APG-API-KEY"] = this.Configuration.GetApiKeyWithPrefix("APG-API-KEY");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PaymentCreate", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AyriaPaymentV1DTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (AyriaPaymentV1DTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AyriaPaymentV1DTO)));
        }

        /// <summary>
        /// Add a new payment 
        /// </summary>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="ayriaPaymentV1Command"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of AyriaPaymentV1DTO</returns>
        public async System.Threading.Tasks.Task<AyriaPaymentV1DTO> PaymentCreateAsync (string APG_WALLET_ID, AyriaPaymentV1Command ayriaPaymentV1Command = default(AyriaPaymentV1Command), CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<AyriaPaymentV1DTO> localVarResponse = await PaymentCreateWithHttpInfoAsync(APG_WALLET_ID, ayriaPaymentV1Command, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Add a new payment 
        /// </summary>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="ayriaPaymentV1Command"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (AyriaPaymentV1DTO)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AyriaPaymentV1DTO>> PaymentCreateWithHttpInfoAsync (string APG_WALLET_ID, AyriaPaymentV1Command ayriaPaymentV1Command = default(AyriaPaymentV1Command), CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'APG_WALLET_ID' is set
            if (APG_WALLET_ID == null)
                throw new ApiException(400, "Missing required parameter 'APG_WALLET_ID' when calling PaymentApi->PaymentCreate");

            var localVarPath = "/create";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (APG_WALLET_ID != null) localVarHeaderParams.Add("APG-WALLET-ID", this.Configuration.ApiClient.ParameterToString(APG_WALLET_ID)); // header parameter
            if (ayriaPaymentV1Command != null && ayriaPaymentV1Command.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(ayriaPaymentV1Command); // http body (model) parameter
            }
            else
            {
                localVarPostBody = ayriaPaymentV1Command; // byte array
            }

            // authentication (APG-API-KEY) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("APG-API-KEY")))
            {
                localVarHeaderParams["APG-API-KEY"] = this.Configuration.GetApiKeyWithPrefix("APG-API-KEY");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PaymentCreate", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AyriaPaymentV1DTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (AyriaPaymentV1DTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AyriaPaymentV1DTO)));
        }

        /// <summary>
        /// Verify payment with referenceCode Returns a single payment
        /// </summary>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="referenceCode">ReferenceCode of payment to verify</param>
        /// <returns>AyriaPaymentV1DTO</returns>
        public AyriaPaymentV1DTO VerifyPaymentByReferenceCode (string APG_WALLET_ID, string referenceCode)
        {
             ApiResponse<AyriaPaymentV1DTO> localVarResponse = VerifyPaymentByReferenceCodeWithHttpInfo(APG_WALLET_ID, referenceCode);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Verify payment with referenceCode Returns a single payment
        /// </summary>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="referenceCode">ReferenceCode of payment to verify</param>
        /// <returns>ApiResponse of AyriaPaymentV1DTO</returns>
        public ApiResponse<AyriaPaymentV1DTO> VerifyPaymentByReferenceCodeWithHttpInfo (string APG_WALLET_ID, string referenceCode)
        {
            // verify the required parameter 'APG_WALLET_ID' is set
            if (APG_WALLET_ID == null)
                throw new ApiException(400, "Missing required parameter 'APG_WALLET_ID' when calling PaymentApi->VerifyPaymentByReferenceCode");
            // verify the required parameter 'referenceCode' is set
            if (referenceCode == null)
                throw new ApiException(400, "Missing required parameter 'referenceCode' when calling PaymentApi->VerifyPaymentByReferenceCode");

            var localVarPath = "/verify/{referenceCode}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (referenceCode != null) localVarPathParams.Add("referenceCode", this.Configuration.ApiClient.ParameterToString(referenceCode)); // path parameter
            if (APG_WALLET_ID != null) localVarHeaderParams.Add("APG-WALLET-ID", this.Configuration.ApiClient.ParameterToString(APG_WALLET_ID)); // header parameter

            // authentication (APG-API-KEY) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("APG-API-KEY")))
            {
                localVarHeaderParams["APG-API-KEY"] = this.Configuration.GetApiKeyWithPrefix("APG-API-KEY");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("VerifyPaymentByReferenceCode", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AyriaPaymentV1DTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (AyriaPaymentV1DTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AyriaPaymentV1DTO)));
        }

        /// <summary>
        /// Verify payment with referenceCode Returns a single payment
        /// </summary>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="referenceCode">ReferenceCode of payment to verify</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of AyriaPaymentV1DTO</returns>
        public async System.Threading.Tasks.Task<AyriaPaymentV1DTO> VerifyPaymentByReferenceCodeAsync (string APG_WALLET_ID, string referenceCode, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<AyriaPaymentV1DTO> localVarResponse = await VerifyPaymentByReferenceCodeWithHttpInfoAsync(APG_WALLET_ID, referenceCode, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Verify payment with referenceCode Returns a single payment
        /// </summary>
        /// <exception cref="com.ayriaplatform.apg.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="APG_WALLET_ID"></param>
        /// <param name="referenceCode">ReferenceCode of payment to verify</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (AyriaPaymentV1DTO)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AyriaPaymentV1DTO>> VerifyPaymentByReferenceCodeWithHttpInfoAsync (string APG_WALLET_ID, string referenceCode, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'APG_WALLET_ID' is set
            if (APG_WALLET_ID == null)
                throw new ApiException(400, "Missing required parameter 'APG_WALLET_ID' when calling PaymentApi->VerifyPaymentByReferenceCode");
            // verify the required parameter 'referenceCode' is set
            if (referenceCode == null)
                throw new ApiException(400, "Missing required parameter 'referenceCode' when calling PaymentApi->VerifyPaymentByReferenceCode");

            var localVarPath = "/verify/{referenceCode}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (referenceCode != null) localVarPathParams.Add("referenceCode", this.Configuration.ApiClient.ParameterToString(referenceCode)); // path parameter
            if (APG_WALLET_ID != null) localVarHeaderParams.Add("APG-WALLET-ID", this.Configuration.ApiClient.ParameterToString(APG_WALLET_ID)); // header parameter

            // authentication (APG-API-KEY) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("APG-API-KEY")))
            {
                localVarHeaderParams["APG-API-KEY"] = this.Configuration.GetApiKeyWithPrefix("APG-API-KEY");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("VerifyPaymentByReferenceCode", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AyriaPaymentV1DTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (AyriaPaymentV1DTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AyriaPaymentV1DTO)));
        }

    }
}
