/* 
 * APG API
 *
 * This is a APG (Ayria Payment Gateway) API SDK.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = com.ayriaplatform.apg.Client.OpenAPIDateConverter;

namespace com.ayriaplatform.apg.Model
{
    /// <summary>
    /// Cancel created payment
    /// </summary>
    [DataContract]
    public partial class AyriaPaymentV1CancelCommand :  IEquatable<AyriaPaymentV1CancelCommand>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AyriaPaymentV1CancelCommand" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AyriaPaymentV1CancelCommand() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AyriaPaymentV1CancelCommand" /> class.
        /// </summary>
        /// <param name="referenceCode">Reference code (required).</param>
        /// <param name="cancelDescription">Cancel description (required).</param>
        public AyriaPaymentV1CancelCommand(string referenceCode = default(string), string cancelDescription = default(string))
        {
            // to ensure "referenceCode" is required (not null)
            if (referenceCode == null)
            {
                throw new InvalidDataException("referenceCode is a required property for AyriaPaymentV1CancelCommand and cannot be null");
            }
            else
            {
                this.ReferenceCode = referenceCode;
            }
            
            // to ensure "cancelDescription" is required (not null)
            if (cancelDescription == null)
            {
                throw new InvalidDataException("cancelDescription is a required property for AyriaPaymentV1CancelCommand and cannot be null");
            }
            else
            {
                this.CancelDescription = cancelDescription;
            }
            
        }
        
        /// <summary>
        /// Reference code
        /// </summary>
        /// <value>Reference code</value>
        [DataMember(Name="referenceCode", EmitDefaultValue=true)]
        public string ReferenceCode { get; set; }

        /// <summary>
        /// Cancel description
        /// </summary>
        /// <value>Cancel description</value>
        [DataMember(Name="cancelDescription", EmitDefaultValue=true)]
        public string CancelDescription { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AyriaPaymentV1CancelCommand {\n");
            sb.Append("  ReferenceCode: ").Append(ReferenceCode).Append("\n");
            sb.Append("  CancelDescription: ").Append(CancelDescription).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AyriaPaymentV1CancelCommand);
        }

        /// <summary>
        /// Returns true if AyriaPaymentV1CancelCommand instances are equal
        /// </summary>
        /// <param name="input">Instance of AyriaPaymentV1CancelCommand to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AyriaPaymentV1CancelCommand input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ReferenceCode == input.ReferenceCode ||
                    (this.ReferenceCode != null &&
                    this.ReferenceCode.Equals(input.ReferenceCode))
                ) && 
                (
                    this.CancelDescription == input.CancelDescription ||
                    (this.CancelDescription != null &&
                    this.CancelDescription.Equals(input.CancelDescription))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ReferenceCode != null)
                    hashCode = hashCode * 59 + this.ReferenceCode.GetHashCode();
                if (this.CancelDescription != null)
                    hashCode = hashCode * 59 + this.CancelDescription.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
