/* 
 * APG API
 *
 * This is a APG (Ayria Payment Gateway) API SDK.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.AyriaPlatform.APG.Client.OpenAPIDateConverter;

namespace Com.AyriaPlatform.APG.Model
{
    /// <summary>
    /// A payment dto created in Ayria platform
    /// </summary>
    [DataContract]
    public partial class AyriaPaymentV1DTO :  IEquatable<AyriaPaymentV1DTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AyriaPaymentV1DTO" /> class.
        /// </summary>
        /// <param name="referralCode">Payee referral code.</param>
        /// <param name="amount">Total price in Riyal currency.</param>
        /// <param name="payerMobile">Payer mobile number.</param>
        /// <param name="trackingNumber">Tracking number.</param>
        /// <param name="referenceCode">Reference code.</param>
        /// <param name="payeeName">Payee name.</param>
        /// <param name="payerName">Payer name.</param>
        /// <param name="description">Description for payment.</param>
        /// <param name="extraData">Extra data related to payment.</param>
        /// <param name="paymentNumber">Payment number (external).</param>
        /// <param name="paid">Payment paid status.</param>
        /// <param name="canceled">Payment cancel status.</param>
        /// <param name="createdDate">Create date of payment.</param>
        /// <param name="paymentUrl">Payment URL.</param>
        /// <param name="cancelDescription">Cancel description.</param>
        /// <param name="issuerMustVerifyPayment">If is &#39;true&#39; issuer must verify payment.</param>
        /// <param name="paymentStatus">Is usually DEFAULT, but can be WAITING_FOR_VERIFY or VERIFIED if issuerMustVerifyPayment is true.</param>
        /// <param name="callbackUrl">Callback url, if is null then default callback url will be used instead.</param>
        /// <param name="kalas">kalas.</param>
        public AyriaPaymentV1DTO(long referralCode = default(long), long amount = default(long), string payerMobile = default(string), long trackingNumber = default(long), string referenceCode = default(string), string payeeName = default(string), string payerName = default(string), string description = default(string), string extraData = default(string), string paymentNumber = default(string), bool paid = default(bool), bool canceled = default(bool), string createdDate = default(string), string paymentUrl = default(string), string cancelDescription = default(string), bool issuerMustVerifyPayment = default(bool), string paymentStatus = default(string), string callbackUrl = default(string), List<AyriaPaymentV1KalaDTO> kalas = default(List<AyriaPaymentV1KalaDTO>))
        {
            this.ReferralCode = referralCode;
            this.Amount = amount;
            this.PayerMobile = payerMobile;
            this.TrackingNumber = trackingNumber;
            this.ReferenceCode = referenceCode;
            this.PayeeName = payeeName;
            this.PayerName = payerName;
            this.Description = description;
            this.ExtraData = extraData;
            this.PaymentNumber = paymentNumber;
            this.Paid = paid;
            this.Canceled = canceled;
            this.CreatedDate = createdDate;
            this.PaymentUrl = paymentUrl;
            this.CancelDescription = cancelDescription;
            this.IssuerMustVerifyPayment = issuerMustVerifyPayment;
            this.PaymentStatus = paymentStatus;
            this.CallbackUrl = callbackUrl;
            this.Kalas = kalas;
        }
        
        /// <summary>
        /// Payee referral code
        /// </summary>
        /// <value>Payee referral code</value>
        [DataMember(Name="referralCode", EmitDefaultValue=false)]
        public long ReferralCode { get; set; }

        /// <summary>
        /// Total price in Riyal currency
        /// </summary>
        /// <value>Total price in Riyal currency</value>
        [DataMember(Name="amount", EmitDefaultValue=false)]
        public long Amount { get; set; }

        /// <summary>
        /// Payer mobile number
        /// </summary>
        /// <value>Payer mobile number</value>
        [DataMember(Name="payerMobile", EmitDefaultValue=false)]
        public string PayerMobile { get; set; }

        /// <summary>
        /// Tracking number
        /// </summary>
        /// <value>Tracking number</value>
        [DataMember(Name="trackingNumber", EmitDefaultValue=false)]
        public long TrackingNumber { get; set; }

        /// <summary>
        /// Reference code
        /// </summary>
        /// <value>Reference code</value>
        [DataMember(Name="referenceCode", EmitDefaultValue=false)]
        public string ReferenceCode { get; set; }

        /// <summary>
        /// Payee name
        /// </summary>
        /// <value>Payee name</value>
        [DataMember(Name="payeeName", EmitDefaultValue=false)]
        public string PayeeName { get; set; }

        /// <summary>
        /// Payer name
        /// </summary>
        /// <value>Payer name</value>
        [DataMember(Name="payerName", EmitDefaultValue=false)]
        public string PayerName { get; set; }

        /// <summary>
        /// Description for payment
        /// </summary>
        /// <value>Description for payment</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Extra data related to payment
        /// </summary>
        /// <value>Extra data related to payment</value>
        [DataMember(Name="extraData", EmitDefaultValue=false)]
        public string ExtraData { get; set; }

        /// <summary>
        /// Payment number (external)
        /// </summary>
        /// <value>Payment number (external)</value>
        [DataMember(Name="paymentNumber", EmitDefaultValue=false)]
        public string PaymentNumber { get; set; }

        /// <summary>
        /// Payment paid status
        /// </summary>
        /// <value>Payment paid status</value>
        [DataMember(Name="paid", EmitDefaultValue=false)]
        public bool Paid { get; set; }

        /// <summary>
        /// Payment cancel status
        /// </summary>
        /// <value>Payment cancel status</value>
        [DataMember(Name="canceled", EmitDefaultValue=false)]
        public bool Canceled { get; set; }

        /// <summary>
        /// Create date of payment
        /// </summary>
        /// <value>Create date of payment</value>
        [DataMember(Name="createdDate", EmitDefaultValue=false)]
        public string CreatedDate { get; set; }

        /// <summary>
        /// Payment URL
        /// </summary>
        /// <value>Payment URL</value>
        [DataMember(Name="paymentUrl", EmitDefaultValue=false)]
        public string PaymentUrl { get; set; }

        /// <summary>
        /// Cancel description
        /// </summary>
        /// <value>Cancel description</value>
        [DataMember(Name="cancelDescription", EmitDefaultValue=false)]
        public string CancelDescription { get; set; }

        /// <summary>
        /// If is &#39;true&#39; issuer must verify payment
        /// </summary>
        /// <value>If is &#39;true&#39; issuer must verify payment</value>
        [DataMember(Name="issuerMustVerifyPayment", EmitDefaultValue=false)]
        public bool IssuerMustVerifyPayment { get; set; }

        /// <summary>
        /// Is usually DEFAULT, but can be WAITING_FOR_VERIFY or VERIFIED if issuerMustVerifyPayment is true
        /// </summary>
        /// <value>Is usually DEFAULT, but can be WAITING_FOR_VERIFY or VERIFIED if issuerMustVerifyPayment is true</value>
        [DataMember(Name="paymentStatus", EmitDefaultValue=false)]
        public string PaymentStatus { get; set; }

        /// <summary>
        /// Callback url, if is null then default callback url will be used instead
        /// </summary>
        /// <value>Callback url, if is null then default callback url will be used instead</value>
        [DataMember(Name="callbackUrl", EmitDefaultValue=false)]
        public string CallbackUrl { get; set; }

        /// <summary>
        /// Gets or Sets Kalas
        /// </summary>
        [DataMember(Name="kalas", EmitDefaultValue=false)]
        public List<AyriaPaymentV1KalaDTO> Kalas { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AyriaPaymentV1DTO {\n");
            sb.Append("  ReferralCode: ").Append(ReferralCode).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  PayerMobile: ").Append(PayerMobile).Append("\n");
            sb.Append("  TrackingNumber: ").Append(TrackingNumber).Append("\n");
            sb.Append("  ReferenceCode: ").Append(ReferenceCode).Append("\n");
            sb.Append("  PayeeName: ").Append(PayeeName).Append("\n");
            sb.Append("  PayerName: ").Append(PayerName).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  ExtraData: ").Append(ExtraData).Append("\n");
            sb.Append("  PaymentNumber: ").Append(PaymentNumber).Append("\n");
            sb.Append("  Paid: ").Append(Paid).Append("\n");
            sb.Append("  Canceled: ").Append(Canceled).Append("\n");
            sb.Append("  CreatedDate: ").Append(CreatedDate).Append("\n");
            sb.Append("  PaymentUrl: ").Append(PaymentUrl).Append("\n");
            sb.Append("  CancelDescription: ").Append(CancelDescription).Append("\n");
            sb.Append("  IssuerMustVerifyPayment: ").Append(IssuerMustVerifyPayment).Append("\n");
            sb.Append("  PaymentStatus: ").Append(PaymentStatus).Append("\n");
            sb.Append("  CallbackUrl: ").Append(CallbackUrl).Append("\n");
            sb.Append("  Kalas: ").Append(Kalas).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AyriaPaymentV1DTO);
        }

        /// <summary>
        /// Returns true if AyriaPaymentV1DTO instances are equal
        /// </summary>
        /// <param name="input">Instance of AyriaPaymentV1DTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AyriaPaymentV1DTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ReferralCode == input.ReferralCode ||
                    (this.ReferralCode != null &&
                    this.ReferralCode.Equals(input.ReferralCode))
                ) && 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                ) && 
                (
                    this.PayerMobile == input.PayerMobile ||
                    (this.PayerMobile != null &&
                    this.PayerMobile.Equals(input.PayerMobile))
                ) && 
                (
                    this.TrackingNumber == input.TrackingNumber ||
                    (this.TrackingNumber != null &&
                    this.TrackingNumber.Equals(input.TrackingNumber))
                ) && 
                (
                    this.ReferenceCode == input.ReferenceCode ||
                    (this.ReferenceCode != null &&
                    this.ReferenceCode.Equals(input.ReferenceCode))
                ) && 
                (
                    this.PayeeName == input.PayeeName ||
                    (this.PayeeName != null &&
                    this.PayeeName.Equals(input.PayeeName))
                ) && 
                (
                    this.PayerName == input.PayerName ||
                    (this.PayerName != null &&
                    this.PayerName.Equals(input.PayerName))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.ExtraData == input.ExtraData ||
                    (this.ExtraData != null &&
                    this.ExtraData.Equals(input.ExtraData))
                ) && 
                (
                    this.PaymentNumber == input.PaymentNumber ||
                    (this.PaymentNumber != null &&
                    this.PaymentNumber.Equals(input.PaymentNumber))
                ) && 
                (
                    this.Paid == input.Paid ||
                    (this.Paid != null &&
                    this.Paid.Equals(input.Paid))
                ) && 
                (
                    this.Canceled == input.Canceled ||
                    (this.Canceled != null &&
                    this.Canceled.Equals(input.Canceled))
                ) && 
                (
                    this.CreatedDate == input.CreatedDate ||
                    (this.CreatedDate != null &&
                    this.CreatedDate.Equals(input.CreatedDate))
                ) && 
                (
                    this.PaymentUrl == input.PaymentUrl ||
                    (this.PaymentUrl != null &&
                    this.PaymentUrl.Equals(input.PaymentUrl))
                ) && 
                (
                    this.CancelDescription == input.CancelDescription ||
                    (this.CancelDescription != null &&
                    this.CancelDescription.Equals(input.CancelDescription))
                ) && 
                (
                    this.IssuerMustVerifyPayment == input.IssuerMustVerifyPayment ||
                    (this.IssuerMustVerifyPayment != null &&
                    this.IssuerMustVerifyPayment.Equals(input.IssuerMustVerifyPayment))
                ) && 
                (
                    this.PaymentStatus == input.PaymentStatus ||
                    (this.PaymentStatus != null &&
                    this.PaymentStatus.Equals(input.PaymentStatus))
                ) && 
                (
                    this.CallbackUrl == input.CallbackUrl ||
                    (this.CallbackUrl != null &&
                    this.CallbackUrl.Equals(input.CallbackUrl))
                ) && 
                (
                    this.Kalas == input.Kalas ||
                    this.Kalas != null &&
                    input.Kalas != null &&
                    this.Kalas.SequenceEqual(input.Kalas)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ReferralCode != null)
                    hashCode = hashCode * 59 + this.ReferralCode.GetHashCode();
                if (this.Amount != null)
                    hashCode = hashCode * 59 + this.Amount.GetHashCode();
                if (this.PayerMobile != null)
                    hashCode = hashCode * 59 + this.PayerMobile.GetHashCode();
                if (this.TrackingNumber != null)
                    hashCode = hashCode * 59 + this.TrackingNumber.GetHashCode();
                if (this.ReferenceCode != null)
                    hashCode = hashCode * 59 + this.ReferenceCode.GetHashCode();
                if (this.PayeeName != null)
                    hashCode = hashCode * 59 + this.PayeeName.GetHashCode();
                if (this.PayerName != null)
                    hashCode = hashCode * 59 + this.PayerName.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.ExtraData != null)
                    hashCode = hashCode * 59 + this.ExtraData.GetHashCode();
                if (this.PaymentNumber != null)
                    hashCode = hashCode * 59 + this.PaymentNumber.GetHashCode();
                if (this.Paid != null)
                    hashCode = hashCode * 59 + this.Paid.GetHashCode();
                if (this.Canceled != null)
                    hashCode = hashCode * 59 + this.Canceled.GetHashCode();
                if (this.CreatedDate != null)
                    hashCode = hashCode * 59 + this.CreatedDate.GetHashCode();
                if (this.PaymentUrl != null)
                    hashCode = hashCode * 59 + this.PaymentUrl.GetHashCode();
                if (this.CancelDescription != null)
                    hashCode = hashCode * 59 + this.CancelDescription.GetHashCode();
                if (this.IssuerMustVerifyPayment != null)
                    hashCode = hashCode * 59 + this.IssuerMustVerifyPayment.GetHashCode();
                if (this.PaymentStatus != null)
                    hashCode = hashCode * 59 + this.PaymentStatus.GetHashCode();
                if (this.CallbackUrl != null)
                    hashCode = hashCode * 59 + this.CallbackUrl.GetHashCode();
                if (this.Kalas != null)
                    hashCode = hashCode * 59 + this.Kalas.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
