/*
 * APG API
 *
 * This is a APG (Ayria Payment Gateway) API SDK.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using com.ayriaplatform.apg.Client;
using com.ayriaplatform.apg.Api;
using com.ayriaplatform.apg.Model;

namespace com.ayriaplatform.apg.Test
{
    /// <summary>
    ///  Class for testing PaymentApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PaymentApiTests
    {
        private PaymentApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            Configuration configuration = new Configuration();
            configuration.AddApiKey("APG-API-KEY", "APG3oNq6T4xJTzPiyaLRBIQqfW8VhswK4a79zGxG1nPM7pPtPO5JXUqooEtxQUxl"); /// CHANGE api key to yours.
            configuration.AddDefaultHeader("APG-WALLET-ID", "10012036"); /// CHANGE wallet id to yours.
            instance = new PaymentApi(configuration);
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PaymentApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' PaymentApi
            //Assert.IsInstanceOf(typeof(PaymentApi), instance);
        }


        /// <summary>
        /// Test GetPaymentByReferenceCode
        /// </summary>
        [Test]
        public void GetPaymentByReferenceCodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            string referenceCode = "1a619f40-2654-4ef8-9161-d52656f14c03";
            var response = instance.GetPaymentByReferenceCode(referenceCode);
            Assert.IsInstanceOf(typeof(AyriaPaymentV1DTO), response, "response is AyriaPaymentV1DTO");
        }
        
        /// <summary>
        /// Test PaymentCancel
        /// </summary>
        [Test]
        public void PaymentCancelTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AyriaPaymentV1CancelCommand ayriaPaymentV1CancelCommand = null;
            //var response = instance.PaymentCancel(ayriaPaymentV1CancelCommand);
            //Assert.IsInstanceOf(typeof(AyriaPaymentV1DTO), response, "response is AyriaPaymentV1DTO");
        }

        /// <summary>
        /// Test PaymentCreate
        /// </summary>
        [Test]
        public void PaymentCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AyriaPaymentV1Command ayriaPaymentV1Command = null;
            //var response = instance.PaymentCreate(ayriaPaymentV1Command);
            //Assert.IsInstanceOf(typeof(AyriaPaymentV1DTO), response, "response is AyriaPaymentV1DTO");
        }

    }

}
