/* 
 * APG API
 *
 * This is a APG (Ayria Payment Gateway) API SDK.
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Com.AyriaPlatform.APG.Client;
using Com.AyriaPlatform.APG.Api;
using Com.AyriaPlatform.APG.Model;

namespace Com.AyriaPlatform.APG.Test
{
    /// <summary>
    ///  Class for testing PaymentApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PaymentApiTests
    {
        private PaymentApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PaymentApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PaymentApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' PaymentApi
            //Assert.IsInstanceOf(typeof(PaymentApi), instance);
        }

        
        /// <summary>
        /// Test GetPaymentByReferenceCode
        /// </summary>
        [Test]
        public void GetPaymentByReferenceCodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string APG_WALLET_ID = null;
            //string referenceCode = null;
            //var response = instance.GetPaymentByReferenceCode(APG_WALLET_ID, referenceCode);
            //Assert.IsInstanceOf(typeof(AyriaPaymentV1DTO), response, "response is AyriaPaymentV1DTO");
        }
        
        /// <summary>
        /// Test GetPayments
        /// </summary>
        [Test]
        public void GetPaymentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string APG_WALLET_ID = null;
            //string page = null;
            //string size = null;
            //string sort = null;
            //string createdDateGreaterThan = null;
            //string createdDateToLessThanOrEqual = null;
            //var response = instance.GetPayments(APG_WALLET_ID, page, size, sort, createdDateGreaterThan, createdDateToLessThanOrEqual);
            //Assert.IsInstanceOf(typeof(List<AyriaPaymentV1DTO>), response, "response is List<AyriaPaymentV1DTO>");
        }
        
        /// <summary>
        /// Test PaymentCancel
        /// </summary>
        [Test]
        public void PaymentCancelTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string APG_WALLET_ID = null;
            //AyriaPaymentV1CancelCommand ayriaPaymentV1CancelCommand = null;
            //var response = instance.PaymentCancel(APG_WALLET_ID, ayriaPaymentV1CancelCommand);
            //Assert.IsInstanceOf(typeof(AyriaPaymentV1DTO), response, "response is AyriaPaymentV1DTO");
        }
        
        /// <summary>
        /// Test PaymentCreate
        /// </summary>
        [Test]
        public void PaymentCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string APG_WALLET_ID = null;
            //AyriaPaymentV1Command ayriaPaymentV1Command = null;
            //var response = instance.PaymentCreate(APG_WALLET_ID, ayriaPaymentV1Command);
            //Assert.IsInstanceOf(typeof(AyriaPaymentV1DTO), response, "response is AyriaPaymentV1DTO");
        }
        
        /// <summary>
        /// Test VerifyPaymentByReferenceCode
        /// </summary>
        [Test]
        public void VerifyPaymentByReferenceCodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string APG_WALLET_ID = null;
            //string referenceCode = null;
            //var response = instance.VerifyPaymentByReferenceCode(APG_WALLET_ID, referenceCode);
            //Assert.IsInstanceOf(typeof(AyriaPaymentV1DTO), response, "response is AyriaPaymentV1DTO");
        }
        
    }

}
